name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore SerpentModding/SerpentModding.csproj
      - name: Build
        run: dotnet build SerpentModding/SerpentModding.csproj --no-restore --configuration Release
      - name: Test
        run: dotnet test SerpentModding.Tests/SerpentModding.Tests.csproj --no-build --configuration Release --verbosity normal
