name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Test
        run: dotnet test SerpentModding.Tests/SerpentModding.Tests.csproj --configuration Release --verbosity normal

  nuget-dry-run:
    needs: build-and-test
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Extract version
        id: get_version
        shell: bash
        run: |
          echo "version=1.0.0" >> $GITHUB_OUTPUT

      - name: Update csproj version
        shell: pwsh
        run: |
          $proj = 'SerpentModding/SerpentModding.csproj'
          $version = '${{ steps.get_version.outputs.version }}'
          if (-not $version) { Write-Error 'No version specified or detected!'; exit 1 }
          $content = Get-Content $proj -Raw
          if ($content -match '<Version>.*</Version>') {
            $content = $content -replace '<Version>.*</Version>', "<Version>$version</Version>"
          } else {
            $content = $content -replace '(<PropertyGroup>)', "`$1`n    <Version>$version</Version>"
          }
          Set-Content $proj $content

      - name: Extract release notes from CHANGELOG.md
        id: changelog
        shell: pwsh
        run: |
          $version = '${{ steps.get_version.outputs.version }}'
          $lines = Get-Content CHANGELOG.md
          $start = ($lines | Select-String "## \[$version\]").LineNumber
          if (-not $start) { Write-Error "No changelog entry for version $version"; exit 1 }
          $startIdx = $start
          $next = ($lines | Select-String "^## \[" | Where-Object { $_.LineNumber -gt $startIdx }) | Select-Object -First 1
          $endIdx = if ($next) { $next.LineNumber - 1 } else { $lines.Count }
          $notes = $lines[($startIdx)..($endIdx - 1)] -join "`n"
          $notes = $notes -replace '^## \[.*\] - .*\r?\n?', ''
          echo "notes<<EOF" >> $env:GITHUB_OUTPUT
          echo "$notes" >> $env:GITHUB_OUTPUT
          echo "EOF" >> $env:GITHUB_OUTPUT

      - name: Update csproj release notes
        shell: pwsh
        run: |
          $proj = 'SerpentModding/SerpentModding.csproj'
          $notes = '${{ steps.changelog.outputs.notes }}'
          $content = Get-Content $proj -Raw
          if ($content -match '<PackageReleaseNotes>.*</PackageReleaseNotes>') {
            $content = $content -replace '<PackageReleaseNotes>.*</PackageReleaseNotes>', "<PackageReleaseNotes>$notes</PackageReleaseNotes>"
          }
          Set-Content $proj $content

      - name: Restore dependencies
        run: dotnet restore SerpentModding/SerpentModding.csproj

      - name: Build
        run: dotnet build SerpentModding/SerpentModding.csproj --configuration Release --no-restore

      - name: Pack
        run: dotnet pack SerpentModding/SerpentModding.csproj --configuration Release --no-build --output nupkg
