name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Test (Release)
        if: ${{ !github.event.pull_request.head.repo.fork && (github.event.inputs.dry_run != 'true' && (inputs.dry_run != true)) }}
        run: dotnet test SerpentModding.Tests/SerpentModding.Tests.csproj --configuration Release --verbosity normal

  nuget-dry-run:
    needs: build-and-test
    uses: ./.github/workflows/nuget-publish.yml
    with:
      version: '1.0.0'
      dry_run: true
