name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Test
        run: dotnet test SerpentModding.Tests/SerpentModding.Tests.csproj --configuration Release --verbosity normal
      - name: Trigger NuGet Dry Run Workflow
        if: ${{ success() }}
        shell: cmd
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST ^
            -H "Accept: application/vnd.github+json" ^
            -H "Authorization: Bearer %GH_TOKEN%" ^
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/nuget-publish.yml/dispatches ^
            -d "{\"ref\":\"${{ github.ref }}\",\"inputs\":{\"version\":\"1.0.0\",\"dry_run\":\"true\"}}"
